workflows:
  ios-swift-package:
    name: iOS Swift Package
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.lucianotheforce.OsConectLocalApp"
        XCODE_SCHEME: "OsConectLocalApp"
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build and archive iOS app
        script: |
          xcodebuild clean archive \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/OsConectLocalApp.xcarchive
      - name: Debug exportOptions.plist
        script: |
          cat exportOptions.plist
      - name: Verify archive
        script: |
          ls -R $CM_BUILD_DIR/OsConectLocalApp.xcarchive
      - name: Check Xcode version
        script: |
          xcodebuild -version
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/OsConectLocalApp.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa \
            -allowProvisioningUpdates \
            -verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
