workflows:
  ios-swift-package:
    name: iOS Swift Package
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build Swift Package
        script: |
          xcodebuild build -scheme OsConectLocalApp -destination 'platform=iOS Simulator,name=iPhone 12'
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM